Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -12,182 +12,191 @@ jobs:
     if: github.event.repository.owner.id == github.event.sender.id
     steps:
     - uses: actions/checkout@v3
-    - name: Setup Configuration
+    - name: Setup Environment Configuration
       run: |
-        echo "KERNEL_SOURCE=$(cat config.env | grep -w "KERNEL_SOURCE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNEL_SOURCE_BRANCH=$(cat config.env | grep -w "KERNEL_SOURCE_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNEL_DEFCONFIG=$(cat config.env | grep -w "KERNEL_DEFCONFIG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "TARGET_ARCH=$(cat config.env | grep -w "TARGET_ARCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNEL_FILE=$(cat config.env | grep -w "KERNEL_FILE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "USE_CUSTOM_CLANG=$(cat config.env | grep -w "USE_CUSTOM_CLANG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "CUSTOM_CLANG=$(cat config.env | grep -w "CUSTOM_CLANG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "CUSTOM_CLANG_BRANCH=$(cat config.env | grep -w "CUSTOM_CLANG_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "CUSTOM_CLANG_BUILD_COMMAND=$(cat config.env | grep -w "CUSTOM_CLANG_BUILD_COMMAND" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
-        echo "CLANG_BRANCH=$(cat config.env | grep -w "CLANG_BRANCH" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "CLANG_VERSION=$(cat config.env | grep -w "CLANG_VERSION" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "BUILD_EXTRA_COMMAND=$(cat config.env | grep -w "EXTRA_BUILD_COMMAND" | head -n 1 | cut -d ":" -f 2)" >> $GITHUB_ENV
-        echo "DISABLE-LTO=$(cat config.env | grep -w "DISABLE-LTO" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "USE_KERNELSU=$(cat config.env | grep -w "USE_KERNELSU" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "KERNELSU_TAG=$(cat config.env | grep -w "KERNELSU_TAG" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "USE_KPROBES=$(cat config.env | grep -w "USE_KPROBES" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "USE_OVERLAYFS=$(cat config.env | grep -w "USE_OVERLAYFS" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "NEED_DTBO=$(cat config.env | grep -w "NEED_DTBO" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "MAKE_BOOT_IMAGE=$(cat config.env | grep -w "MAKE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
-        echo "SOURCE_BOOT_IMAGE=$(cat config.env | grep -w "SOURCE_BOOT_IMAGE" | head -n 1 | cut -d "=" -f 2)" >> $GITHUB_ENV
+        sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
+                    git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
+                    lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev \
+                    libssl-dev libxml2 libxml2-utils lzop pngcrush schedtool \
+                    squashfs-tools xsltproc zip zlib1g-dev unzip  
+      
 
-    - name: Setup build kernel environment
+    - name: Download kernel source code
       run: |
+        mkdir -p $GITHUB_WORKSPACE/kernel/source
         echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
-        echo "DEVICE=$(echo ${{ env.KERNEL_DEFCONFIG }} | sed 's!vendor/!!;s/_defconfig//;s/_user//;s/-perf//')" >> $GITHUB_ENV
-        sudo apt-get update
-        sudo apt-get install git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3
-        mkdir -p $GITHUB_WORKSPACE/kernel_workspace
+        cd $GITHUB_WORKSPACE/kernel/source
+        git clone -b android-msm-wahoo-4.4-android11  --depth=1 https://android.googlesource.com/kernel/msm
+        cd ./msm
+   
+    - name: Download AnyKernel3
+      run: |
+        cd $GITHUB_WORKSPACE/kernel/source/msm
+        git clone --depth=1 https://github.com/osm0sis/AnyKernel3.git
+        cd ./AnyKernel3
+        sed -i 's@kernel.string=ExampleKernel by osm0sis@KernelSU backport by Cyanide-zh@g' anykernel.sh
+        sed -i 's@device.name1=maguro@device.name3=walleye@g' anykernel.sh
+        sed -i 's@device.name2=toro@device.name2=taimen@g' anykernel.sh
+        sed -i 's@device.name3=toroplus@device.name3=@g' anykernel.sh
+        sed -i 's@device.name4=tuna@device.name4=@g' anykernel.sh
+        sed -i 's@BLOCK=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot@BLOCK=/dev/block/bootdevice/by-name/boot@g' anykernel.sh
+        sed -i 's@IS_SLOT_DEVICE=0@IS_SLOT_DEVICE=1@g' anykernel.sh
 
-    - name: Download Clang-aosp and Gcc-aosp
-      if: env.USE_CUSTOM_CLANG == 'false'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        mkdir clang-aosp
-        wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/${{ env.CLANG_BRANCH }}/clang-${{ env.CLANG_VERSION }}.tar.gz
-        tar -C clang-aosp/ -zxvf clang-${{ env.CLANG_VERSION }}.tar.gz
-        mkdir gcc-aosp
-        wget https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/+archive/refs/tags/android-12.1.0_r27.tar.gz
-        tar -C gcc-aosp/ -zxvf android-12.1.0_r27.tar.gz
 
-    - name: Download Custom-Clang
-      if: env.USE_CUSTOM_CLANG == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        if [[ ${{ env.CUSTOM_CLANG }} =~ github ]]; then
-            git clone ${{ env.CUSTOM_CLANG }} -b ${{ env.CUSTOM_CLANG_BRANCH }} clang-aosp
-        else
-            wget -O clang.zip ${{ env.CUSTOM_CLANG }}
-            mkdir clang-aosp
-            unzip clang.zip -d clang-aosp/
-        fi
 
-    - name: Download mkbootimg tools
-      if: env.MAKE_BOOT_IMAGE == 'true'
+    - name: Download KernelSU
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone https://android.googlesource.com/platform/system/tools/mkbootimg tools -b master-kernel-build-2022 --depth=1
+        cd $GITHUB_WORKSPACE/kernel/source/msm
+        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
+        bash kernelsu-setup.sh
 
-    - name: Download kernel source
+    - name: Edit defconfig
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone ${{ env.KERNEL_SOURCE }} -b ${{ env.KERNEL_SOURCE_BRANCH }} android-kernel --depth=1
+        echo 'CONFIG_KPROBES=y' >> ./arch/arm64/configs/msm-perf_defconfig
+        echo 'CONFIG_HAVE_KPROBES=y' >> ./arch/arm64/configs/msm-perf_defconfig
+        echo 'CONFIG_KPROBE_EVENTS=y' >> ./arch/arm64/configs/msm-perf_defconfig
 
-    - name: Download source boot image
-      if: env.MAKE_BOOT_IMAGE == 'true'
+
+    - name: Download toolchain
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        wget -O boot-source.img ${{ env.SOURCE_BOOT_IMAGE }}
-        if [ -f boot-source.img ]; then
-            echo "FORMAT_MKBOOTING=$(echo `tools/unpack_bootimg.py --boot_img=boot-source.img --format mkbootimg`)" >> $GITHUB_ENV
-            echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
-        fi
-  
-    - name: Setup KernelSU
-      if: env.USE_KERNELSU == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s ${{ env.KERNELSU_TAG }}
-        if [ ${{ env.USE_KPROBES }} = true ]; then
-            echo "CONFIG_MODULES=y" >> arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-            echo "CONFIG_KPROBES=y" >> arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-            echo "CONFIG_HAVE_KPROBES=y" >> arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-            echo "CONFIG_KPROBE_EVENTS=y" >> arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-        fi
-        if [ ${{ env.USE_OVERLAYFS }} = true ]; then
-            echo "CONFIG_OVERLAY_FS=y" >> arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-        fi
-        if [ ${{ env.DISABLE-LTO }} = true ]; then
-            sed -i 's/CONFIG_LTO=y/CONFIG_LTO=n/' arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-            sed -i 's/CONFIG_LTO_CLANG=y/CONFIG_LTO_CLANG=n/' arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-            sed -i 's/CONFIG_THINLTO=y/CONFIG_THINLTO=n/' arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-            echo "CONFIG_LTO_NONE=y" >> arch/${{ env.TARGET_ARCH }}/configs/${{ env.KERNEL_DEFCONFIG }}
-        fi
-        echo "UPLOADNAME=-KernelSU" >> $GITHUB_ENV
+        mkdir -p $GITHUB_WORKSPACE/kernel/toolchains && cd $GITHUB_WORKSPACE/kernel/toolchains 
+        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9.git gcc-arm-4.9
+        mkdir -p ./clang-14 && cd clang-14
+        wget https://github.com/ZyCromerZ/Clang/releases/download/14.0.6-20240212-release/Clang-14.0.6-20240212.tar.gz
+        tar -zxvf Clang-*.tar.gz
 
     - name: Build kernel
       run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang-aosp/bin:$PATH
-        export KBUILD_BUILD_HOST=Github-Action
-        export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
-        make -j$(nproc --all) O=out ARCH=${{ env.TARGET_ARCH }} ${{ env.CUSTOM_CLANG_BUILD_COMMAND }} CC=clang ${{ env.BUILD_EXTRA_COMMAND }} ${{ env.KERNEL_DEFCONFIG }}
-        make -j$(nproc --all) O=out ARCH=${{ env.TARGET_ARCH }} ${{ env.CUSTOM_CLANG_BUILD_COMMAND }} CC=clang ${{ env.BUILD_EXTRA_COMMAND }}
+        cd $GITHUB_WORKSPACE/kernel/source/msm
+        starttime=$(date  +"%Y-%m-%d_%H-%M-%S")
+        #!/bin/bash
+        cinfo="\x1b[38;2;79;155;250m"
+        cwarn="\x1b[38;2;255;200;97m"
+        cerror="\x1b[38;2;240;96;96m"
+        cno="\x1b[0"
 
-    - name: Check a kernel output files
-      run: |
-       cd $GITHUB_WORKSPACE/kernel_workspace
-       if [ -f android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/${{ env.KERNEL_FILE }} ]; then
-           echo "CHECK_FILE_IS_OK=true" >> $GITHUB_ENV
-       else
-           echo "Kernel output file is empty"
-           exit 1
-       fi
-       if [ ${{ env.NEED_DTBO }} = true ]; then
-           if [ -f android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/dtbo.img ]; then
-               echo "CHECK_DTBO_IS_OK=true" >> $GITHUB_ENV
-           else
-               echo "DTBO image is empty"
-               exit 1
-           fi
-       fi
-  
-    - name: Make Anykernel3
-      if: env.CHECK_FILE_IS_OK == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        git clone https://github.com/osm0sis/AnyKernel3
-        sed -i 's/do.devicecheck=1/do.devicecheck=0/g' AnyKernel3/anykernel.sh
-        sed -i 's!block=/dev/block/platform/omap/omap_hsmmc.0/by-name/boot;!block=auto;!g' AnyKernel3/anykernel.sh
-        sed -i 's/is_slot_device=0;/is_slot_device=auto;/g' AnyKernel3/anykernel.sh
-        cp android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/${{ env.KERNEL_FILE }} AnyKernel3/
-        if [ ${{ env.CHECK_DTBO_IS_OK }} = true ]; then
-            cp android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/dtbo.img AnyKernel3/
+
+        echo -e "${cinfo}=============== Setup Some Export ===============${cno}"
+# 内核工作目录
+        export KERNEL_DIR=$(pwd)
+# 内核 defconfig 文件
+        export KERNEL_DEFCONFIG=msm-perf_defconfig
+# 编译临时目录，避免污染根目录
+        export OUT=out
+# anykernel3 目录
+        export ANYKERNEL3=${KERNEL_DIR}/AnyKernel3
+# 内核 zip 刷机包名称
+        export KERNEL_ZIP_NAME="KernelSU_"$(date  +"%Y-%m-%d")".zip"
+# 刷机包打包完成后移动目录
+        export KERNEL_ZIP_EXPORT=$GITHUB_WORKSPACE/kernel
+# clang 绝对路径
+        export CLANG_PATH=$GITHUB_WORKSPACE/kernel/toolchains/zyc-clang
+        export PATH=${CLANG_PATH}/bin:${PATH}
+        export CLANG_TRIPLE=aarch64-linux-gnu-
+# arch平台，这里时arm64
+        export ARCH=arm64
+        export SUBARCH=arm64
+# 只使用clang编译需要配置
+        export LLVM=1
+        export BUILD_INITRAMFS=1
+
+# 编译时线程指定，默认单线程，可以通过参数指定，比如4线程编译
+# ./build.sh 8
+        TH_COUNT=8
+        if [[ "" != "$1" ]]; then
+                TH_NUM=$1
         fi
-        rm -rf AnyKernel3/.git* AnyKernel3/README.md
 
-    - name: Make boot image
-      if: env.HAVE_SOURCE_BOOT_IMAGE == 'true' && env.CHECK_FILE_IS_OK == 'true'
-      run: |
-        cd $GITHUB_WORKSPACE/kernel_workspace
-        tools/unpack_bootimg.py --boot_img boot-source.img
-        cp android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/${{ env.KERNEL_FILE }} out/kernel
-        tools/mkbootimg.py ${{ env.FORMAT_MKBOOTING }} -o boot.img
-        if [ -f boot.img ]; then
-            echo "MAKE_BOOT_IMAGE_IS_OK=true" >> $GITHUB_ENV
+# 编译参数
+        export DEF_ARGS="O=${OUT} \
+                                        CC=clang \
+                                        CXX=clang++ \
+                                        ARCH=${ARCH} \
+                                        CROSS_COMPILE=${CLANG_PATH}/bin/aarch64-linux-gnu- \
+                                        CROSS_COMPILE_ARM32=${CLANG_PATH}/bin/arm-linux-gnueabi- \
+                                        LD=ld.lld "
+        export BUILD_ARGS="-j${TH_COUNT} ${DEF_ARGS}"
+
+        echo -e "${cwarn}kernel workspace dir is => ${KERNEL_DIR}"
+        echo -e "kernel build defonfig is => ${KERNEL_DEFCONFIG}"
+        echo -e "build tmpdir is => ${KERNEL_DIR}/${OUT}"
+        echo -e "anykernel3 workspace dir is => ${ANYKERNEL3}"
+        echo -e "kernel zip name is => ${KERNEL_ZIP_NAME}"
+        echo -e "kernel zip export dir is => ${KERNEL_ZIP_EXPORT}"
+        echo -e "clang path is => ${CLANG_PATH}"
+        echo -e "build arch/subarch is => ${ARCH} / ${SUBARCH}${cno}"
+        # 等待5s，查看配置文件信息是否正确
+        sleep 5s
+
+        echo -e "${cinfo}=============== Make defconfig ===============${cno}"
+# make defconfig
+        make ${DEF_ARGS} ${KERNEL_DEFCONFIG}
+# 如果命令没有出错，继续执行，否则退出编译
+        if [[ "0" != "$?" ]]; then
+                echo -e "${cerror}>>> make defconfig error, build stop!${cno}"
+                exit 1
+        fi
+
+        echo -e "${cinfo}=============== Make Kernel  ===============${cno}"
+        make ${BUILD_ARGS}
+        if [[ "0" != "$?" ]]; then
+                echo -e "${cerror}>>> build kernel error, build stop!${cno}"
+                exit 1
+        fi
+        echo -e "${cwarn}>>> build kernel success${cno}"
+        sleep 3s
+
+# 使用 Anykernel3 制作刷机包
+        echo -e "${cinfo}=============== Make Kernel Zip ==============="
+        if test -e ${ANYKERNEL3}; then
+                if test -e ${KERNEL_DIR}/${OUT}/arch/${ARCH}/boot/dtbo.img; then
+                        if test -e ${KERNEL_DIR}/${OUT}/arch/${ARCH}/boot/Image.gz-dtb; then
+                                echo -e "${cwarn}move kernel files . . .${cno}"
+                                cp ${KERNEL_DIR}/${OUT}/arch/${ARCH}/boot/dtbo.img ${ANYKERNEL3}/
+                                cp ${KERNEL_DIR}/${OUT}/arch/${ARCH}/boot/Image.gz-dtb ${ANYKERNEL3}/
+                                echo -e "${cwarn}into anykernel3 workdir. . ."
+                                cd ${ANYKERNEL3}
+                                if test -e ./Image.gz-dtb; then
+                                        zip -r ${KERNEL_ZIP_NAME} ./*
+                                        test -e ./${KERNEL_ZIP_NAME} && mv ./${KERNEL_ZIP_NAME} ${KERNEL_ZIP_EXPORT}
+                                        echo -e "${cwarn} clean kernel files. . .${cno}"
+                                        test -e ./Image.gz-dtb && rm ./Image.gz-dtb
+                                        test -e ./dtbo.img && rm ./dtbo.img
+                                else
+                                        echo -e "${cerror}stop make => kernel file not found!${cno}"
+                                        exit 1
+                                fi
+                        else
+                                echo -e "${cerror}stop make => Image.gz-dtb not found${cno}"
+                                exit 1
+                        fi
+                else
+                        echo -e "${cerror}stop make => dtbo.img not found${cno}"
+                        exit 1
+                fi
         else
-            echo "Boot image is empty"
+                echo -e "${cerror}stop build => anykernel3 dir not found${cno}"
+                exit 1
+        fi
+        exit 0
+
+        if [ -f ./KernelSU_"$(date  +"%Y-%m-%d")".zip" ]; then
+            echo "BUILD_KERNEL_IS_OK=true" >> $GITHUB_ENV
+        else
+            echo "BUILD ERROR!"
             exit 1
         fi
-    
-    - name: Upload ${{ env.KERNEL_FILE }}
-      if: env.CHECK_FILE_IS_OK == 'true'
-      uses: actions/upload-artifact@v3
-      with:
-        name: ${{ env.KERNEL_FILE }}${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
-        path: kernel_workspace/android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/${{ env.KERNEL_FILE }}
+        endtime=$(date  +"%Y-%m-%d_%H-%M-%S")
+        start_seconds=$(date --date=" $starttime" +%s);
+        end_seconds=$(date --date="$endtime" +%s);
+        echo Start: $starttime.
+        echo End: $endtime.
+        echo "Build Time: "$((end_seconds-start_seconds))"s."
+        
 
-    - name: Upload AnyKernel3
-      if: env.CHECK_FILE_IS_OK == 'true'
+    - name: Upload Kernel
+      if: env.BUILD_KERNEL_IS_OK == 'true'
       uses: actions/upload-artifact@v3
       with:
-        name: AnyKernel3${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
-        path: kernel_workspace/AnyKernel3/*
-
-    - name: Upload DTBO image
-      if: env.CHECK_DTBO_IS_OK == 'true'
-      uses: actions/upload-artifact@v3
-      with:
-        name: dtbo-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
-        path: kernel_workspace/android-kernel/out/arch/${{ env.TARGET_ARCH }}/boot/dtbo.img
-
-    - name: Upload boot image
-      if: env.MAKE_BOOT_IMAGE_IS_OK == 'true'
-      uses: actions/upload-artifact@v3
-      with:
-        name: boot${{ env.UPLOADNAME }}-${{ env.DEVICE }}-${{ env.BUILD_TIME }}
-        path: kernel_workspace/boot.img
+        name: KernelSU.zip
+        path: kernel
